# -*- coding: utf-8 -*-
"""Configuration file for the Sphinx documentation builder.

This file contains the configuration for generating documentation
for the Navigation Lights Photometric Analysis application.
"""

import os
import sys

# -- Path setup --------------------------------------------------------------

# Add the project root to sys.path to import modules
sys.path.insert(0, os.path.abspath('../..'))


# -- Project information -----------------------------------------------------

project = 'Analyse Photométrique Feux Navigation'
copyright = '2024, Votre Nom'
author = 'Votre Nom'

# The full version, including alpha/beta/rc tags
release = '1.0.0'
version = '1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here
extensions = [
    'sphinx.ext.autodoc',           # Core: auto-generate doc from docstrings
    'sphinx.ext.napoleon',          # Support for Google & NumPy docstrings
    'sphinx.ext.viewcode',          # Add links to highlighted source code
    'sphinx.ext.todo',              # Support for TODO items
    'sphinx.ext.coverage',          # Check documentation coverage
    'sphinx.ext.mathjax',           # Math equations support
    'sphinx.ext.intersphinx',       # Link to other project docs
    'sphinx.ext.autosummary',       # Generate autodoc summaries
    'sphinx_autodoc_typehints',     # Better type hints support
]

# Add any paths that contain templates here
templates_path = ['_templates']

# The language for content autogenerated by Sphinx
language = 'fr'

# List of patterns to exclude
exclude_patterns = []


# -- Extension configuration -------------------------------------------------

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}
autodoc_typehints = 'description'
autodoc_typehints_description_target = 'documented'

# Autosummary settings
autosummary_generate = True

# Todo settings
todo_include_todos = True

# Intersphinx mapping
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
}


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# Custom sidebar templates
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = '_static/logo.png'

# The name of an image file (relative to this directory) to use as a favicon
# html_favicon = '_static/favicon.ico'

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer
html_show_copyright = True

# Output file base name for HTML help builder
htmlhelp_basename = 'AnalysePhotometriquedoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '10pt',
    'preamble': r'''
        \usepackage[utf8]{inputenc}
        \usepackage[french]{babel}
    ''',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    ('index', 'AnalysePhotometrique.tex',
     'Documentation Analyse Photométrique',
     'Votre Nom', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page
man_pages = [
    ('index', 'analysephotometrique',
     'Documentation Analyse Photométrique',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    ('index', 'AnalysePhotometrique',
     'Documentation Analyse Photométrique',
     author, 'AnalysePhotometrique',
     'Application d\'analyse photométrique des feux de navigation.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

epub_title = project
epub_exclude_files = ['search.html']


# -- Custom CSS --------------------------------------------------------------

def setup(app):
    """Add custom CSS if needed."""
    # app.add_css_file('custom.css')
    pass
